# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
julia:
- 1.3
os:
- linux
- osx
notifications:
  email: false
# matrix:
#   allow_failures:
#     - julia: nightly
#   fast_finish: true
# after_success:
#   - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
# jobs:
#   include:
#     - stage: Documentation
#       julia: 1.0
#       script: julia --project=docs -e '
#           using Pkg;
#           Pkg.develop(PackageSpec(path=pwd()));
#           Pkg.instantiate();
#           include("docs/make.jl");'
#       after_success: skip
